sudo: required

services:
  - docker

env:
  matrix:
    - UTIL="sshd"
    - UTIL="phpcs"

before_script:
  - docker version
  - cd ${UTIL}

script:
  - docker build -t ${UTIL} .

after_script:
  - docker images
