no-warnings: false
errors: true
no-recursion: false
sniff: false
interactive: false
explain: false
progress: false
colors: true
standard: "$HOME/.composer/vendor/drupal/coder/coder_sniffer/Drupal"
report: full
report-checkstyle: "/root/checkstyle-result.xml"
ignore:
  - *.ignore
  # - */static/*
extensions:
  - php
  - module
  - inc
  - install
  - test
  - profile
  - theme
  - js
  - css
  - info
  - txt
files:
  - ./
  # - ./sites/all/modules/custom
  # - ./sites/all/themes/custom
  # - ./modules/custom
  # - ./themes/custom
